# Generated by Django 6.0.7 on 2026-08-04 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('kmeans', 'KMeans')], max_length=50)),
                ('target_column', models.CharField(blank=True, max_length=100)),
                ('feature_columns', models.JSONField()),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
