# Generated by Django 6.0.7 on 2026-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='r2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='algorithm',
            field=models.CharField(choices=[('Linear Regression', 'Linear Regression')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='feature_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='trained_models/'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='target_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
